services:
  site:
    network_mode: "host"
    container_name: aurora-docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:3953ec6a2c10154a58ccf4ba48083ddfe3f8641d63f0d1d5cb8a4a78169123a7
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
