services:
  site:
    network_mode: "host"
    container_name: aurora-docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:c69f4e0640e5b065f2694579793e4309f1e0e49868b0f2fea29c44d9c0dc2caf
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
