services:
  site:
    network_mode: "host"
    container_name: aurora-docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:f5d1cc40abc10c2843339a2134d07817cf33c405cb16bfd052b0ed790254c3a3
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
