name: check-spelling

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.fedora_version }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check for typos
        uses: crate-ci/typos@8f11c0dc0f31c780c45b3dd5b72ff4b48a350b75 # version 1.0.4
        with:
          files: ./README.md ./docs
          config: ./typos.toml
